### ISSUE TITLE
poe-ui-create exits with error

### ISSUE THREAD

**Issue by padwasabimasala** [poegroup/poe-ui#13]
✧ matthew.thorley@TRS-82 vision-programs-ui poe-ui-create
project: (vision-programs-ui)
description: (A poe app) performance programs ui
organization: (Matthew Thorley) octanner
Installing dependencies. This may take awhile.
poe-ui@0.4.15 ../node_modules/poe-ui
├── simple-http-proxy@0.5.11 (debug@0.7.4)
├── envs@0.1.6 (debug@0.8.1, require-component@0.1.1)
├── passport-oauth2@1.1.2 (uid2@0.0.3, passport-strategy@1.0.0, oauth@0.9.12)
├── passport@0.1.18 (pause@0.0.1, pkginfo@0.2.3)
└── poe-ui-kit@0.2.19 (utils-merge@1.0.0, component-require2@1.1.1, clean-css@2.2.23, simple-assets@0.1.1, uglify-js@2.4.16, stylus@0.49.3, nib@1.0.4, jshint@2.5.11, jade@1.9.0, simple-stack-common@0.2.3, poe-ui-builder@0.1.6)
Makefile:2: node_modules/poe-ui/tasks.mk: No such file or directory
make: **\* No rule to make target `node_modules/poe-ui/tasks.mk'.  Stop.
-!- matthew.thorley@TRS-82 vision-programs-ui echo $?
2

**Comment by mndvns** [comment]
multiple tries and i can't reproduce. make sure you run `npm install` prior to `make`; it think that's what's happening here.

i'm putting together more and better docs, so i'll update instructions. or better yet, add a task to the makefile.

:rooster:

**Comment by camshaft** [comment]
this functionality has been moved to https://github.com/poegroup/poe-cli
